name: 'Run Job Seeker Action'
description: 'A GitHub Action that go through job website's, extract all jobs and insert in notion.so'
on:
  workflow_dispatch:
  push:
  schedule:
  - cron: '0 */12 * * * '

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Run Job Seeker Python File
      id: job-seeker
      run: python job-seeker.py
      shell: bash
