name: 'Run Job Seeker Action'
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
'on':
  workflow_dispatch: {}
  push: {}
  schedule:  
    - cron: '0 */12 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Run Job Seeker Python File
      id: job-seeker
      run: python job-seeker.py
      shell: bash
