name: 'Run Job Seeker Action'
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

'on':
  workflow_dispatch: {}
  push: {}
  schedule:  
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Run Job Seeker Python File 
        run: |
          python src/job-seeker.py
      
      - name: Commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
