name: 'Run Job Seeker Action'
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
'on':
  workflow_dispatch: {}
  push: {}
  schedule:  
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job Seeker Python File 
        uses: actions/checkout@v2
        run: |
          python ./job-seeker.py
